name: Build AITweaker on Main

on:
  push:
    branches:
      - 'main'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PyInstaller build
      run: python build.py

    - name: Zip the build output
      run: |
        $SourceDir = "dist/AITweaker"
        $DestinationZip = "AITweaker-main-windows.zip"
        Compress-Archive -Path $SourceDir -DestinationPath $DestinationZip
      shell: pwsh

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AITweaker-windows-build
        path: AITweaker-main-windows.zip
