name: Build AITweaker on Main

on:
  push:
    branches:
      - 'main'

jobs:
  build-windows:
    runs-on: windows-latest
    
    # Add this permissions block
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PyInstaller build
      run: python build.py

    - name: Zip the build output
      run: |
        $SourceDir = "dist"
        $DestinationZip = "AITweaker-main-windows.zip"
        Compress-Archive -Path $SourceDir -DestinationPath $DestinationZip
      shell: pwsh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AITweaker-Windows
        path: AITweaker-main-windows.zip

    - name: Create Release
      id: create_release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        name: Release ${{ github.sha }}
        draft: false
          prerelease: false
          files: AITweaker-main-windows.zip
