name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create virtual environment
      run: python -m venv venv

    - name: Install dependencies
      run: |
        .\venv\Scripts\python.exe -m pip install --upgrade pip
        .\venv\Scripts\pip.exe install -r requirements.txt
      shell: pwsh

    - name: Build application
      run: .\venv\Scripts\python.exe setup.py build
      shell: pwsh

    - name: Get release name
      id: get_release_name
      run: echo "name=$(Get-Date -Format 'yyyy-MM-dd-HH-mm')" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Archive build output
      id: archive
      run: |
        $output_dir = (Get-ChildItem -Path build -Directory -Filter "exe.*").FullName
        $zip_path = "release-${{ steps.get_release_name.outputs.name }}.zip"
        Compress-Archive -Path "$output_dir\*" -DestinationPath $zip_path
        echo "path=$zip_path" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: "${{ steps.archive.outputs.path }}"
        tag_name: "release-${{ steps.get_release_name.outputs.name }}"
        name: "Release ${{ steps.get_release_name.outputs.name }}"
        body: "Automated release build."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
